### ISSUE TITLE
Build image without ONBUILD

### ISSUE THREAD

**Issue by saulshanabrook** [themattrix/docker-tox#2]
Would it be possible to add an image without the ONBUILD commands?

They are failing for me because I need to install some mysql support on the machine first, before `pip install` will work.

**Comment by saulshanabrook** [comment]
Nevermind, I am just going to copy some stuff from your dockerfile, instead of extending from it.

**Comment by themattrix** [comment]
That sounds like a useful use-case! I'd like to support optionally installing system prerequisites, but I can't think of a good way. The ideal solution would be to add an extra `ONBUILD` command before running `tox`. Perhaps running an `install-prereqs.sh` script, if present. The problem is that I don't want to require the script to exist, yet `ADD`/`COPY` would require exactly that. There might be a way to conditionally add it into the image with globbing, but I'll have to play around with it.

Thoughs?

**Comment by saulshanabrook** [comment]
I ended up doing things a bit differently for [django-fake-model](https://github.com/erm0l0v/django-fake-model). I [didn't install any dependencies with Tox during the docker build](https://github.com/erm0l0v/django-fake-model/blob/master/Dockerfile). Then I [added a data only container in Docker Compose](https://github.com/erm0l0v/django-fake-model/blob/master/docker-compose.yml#L13-L21) that holds the `.tox` and `~/.cache` directory. So you can just run `docker-compose run --rm test tox -e py26-dj16-sqlite-nose` to run a specific environment or `docker-compose run --rm test tox` to run all of them. All pip installs are cached also by default, once I upgraded pip.

But that is tangential to the question of how to add dependencies to the Dockerfile. What happens if you do a `ONBUILD COPY path` and the path doesn't exist?

**Comment by themattrix** [comment]
Aha! This blows up:

``` dockerfile
ONBUILD ADD install-prereqs.sh requirements*.txt tox.ini /app/
```

But this works:

``` dockerfile
ONBUILD ADD install-prereqs*.sh requirements*.txt tox.ini /app/
```

**Comment by saulshanabrook** [comment]
Oh yeah cool, that makes sense!

**Comment by themattrix** [comment]
I pushed the `ONBUILD` change and made some other tweaks too. What do you think of the diff in the link above? I took some inspiration from your Dockerfile as well!

**Comment by saulshanabrook** [comment]
@themattrix that looks great, I just [added one comment](https://github.com/themattrix/docker-tox/commit/e1f3000728e0597ed1cb8eadbb80eb7c08f33e92#commitcomment-15138276).
