### ISSUE TITLE
OSError: [Errno 2] No such file or directory with Python 2.7 (only!) 

### ISSUE THREAD

**Issue by bittner** [themattrix/docker-tox#7]
I do get an error for a `tox` run with Python 2.7 only, whereas all other tox targets execute successfully and also both my local `tox` execution and matrix builds on Travis pass successfully.

``` Python
app_1  | ERROR: invocation failed (errno 2), args: ['/app/.tox/py27/bin/pip', 'freeze'], cwd: /app
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/bin/tox", line 11, in <module>
app_1  |     sys.exit(cmdline())
app_1  |   File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 39, in main
app_1  |     retcode = Session(config).runcommand()
app_1  |   File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 375, in runcommand
app_1  |     return self.subcommand_test()
app_1  |   File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 540, in subcommand_test
app_1  |     action=action)
app_1  |   File "/usr/local/lib/python2.7/dist-packages/tox/venv.py", line 362, in _pcall
app_1  |     redirect=redirect, ignore_ret=ignore_ret)
app_1  |   File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 136, in popen
app_1  |     stdout=stdout, stderr=STDOUT)
app_1  |   File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 224, in _popen
app_1  |     stdout=stdout, stderr=stderr, env=env)
app_1  |   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
app_1  |     errread, errwrite)
app_1  |   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
app_1  |     raise child_exception
app_1  | OSError: [Errno 2] No such file or directory
painlesscontinuousdelivery_app_1 exited with code 1
```

I'm not sure what's happening. The error doesn't seem to have anything to do with [my test code](https://github.com/painless-software/painless-continuous-delivery/blob/master/tests/test_project_generation.py) or the [tox configuration](https://github.com/painless-software/painless-continuous-delivery/blob/master/tox.ini).

Again, all the other targets (Python versions 3.3, 3.4, 3.5 and static code analysis runs) execute successfully and pass. I'm using only a [Docker Compose configuration](https://github.com/painless-software/painless-continuous-delivery/blob/master/docker-compose.yml), is this okay?

**Comment by themattrix** [comment]
Sorry for my extremely-delayed response! Is this still an issue? I recently pushed a new version which uses [pyenv](https://github.com/yyuu/pyenv) to manage the Python versions instead of the [deadsnakes PPA](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes), so that may have changed things.

**Comment by bittner** [comment]
I'm not sure but I think this is still an issue. It looks like I managed to work around the issue in some way, not sure what it was, though. My [Bitbucket Pipelines configuration](https://github.com/painless-software/painless-continuous-delivery/blob/master/bitbucket-pipelines.yml) and [Codeship Services](https://github.com/painless-software/painless-continuous-delivery/blob/master/codeship-services.yml) along with [Codeship Steps](https://github.com/painless-software/painless-continuous-delivery/blob/master/codeship-steps.yml) seem to work reliably. (See/click the badges on the project [README](https://github.com/painless-software/painless-continuous-delivery#painless-continuous-delivery).)

The only, and seemingly related, commit from the day I opened this issue is https://github.com/painless-software/painless-continuous-delivery/commit/9a7e71de7a41a5f19f42ec575285acf07a35e467. That change doesn't ring a bell, does it? Today I'm using the above-mentioned `codeship-services.yml` file instead.

Too bad I didn't add specific information on how to reproduce the issue.
Closing it now for lack of reproducibility.
